version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: control_point
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/control_point
      - PORT=3333
      - ORIGIN_URL=http://localhost:5173
      - JWT_SECRET=asdjasoidjasoidahsdklL
      - JWT_EXPIRES_IN=1h
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npm run dev"

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3333/api
      - VITE_APP_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install --legacy-peer-deps && npm run dev"

volumes:
  pgdata:
