version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: control_point
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/control_point
      - PORT=3333
      - ORIGIN_URL=http://localhost
      - JWT_SECRET=asdjasoidjasoidahsdklL
      - JWT_EXPIRES_IN=1h
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: http://localhost:3333/api
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3333/api

volumes:
  pgdata:
